---
apiVersion: v1
kind: Namespace
metadata:
  name: store
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: store
  name: newrelic
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/metrics"
    - "nodes/stats"
    - "nodes/proxy"
    - "pods"
    - "services"
    - "endpoints"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "namespaces"
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"
    - "daemonsets"
    - "statefulsets"
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - "jobs"
    - "cronjobs"
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
    - "/metrics"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic
  namespace: store
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: store
  name: newrelic-infrastructure
  labels:
    app: newrelic-infrastructure
spec:
  selector:
    matchLabels:
      name: newrelic-infrastructure
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: newrelic-infrastructure
      annotations:
        # Annotation to restart pods if the configmap changes
        checksum/nri-kubernetes: 8a5d3a3c56cc8b3cc301e80de9d1b1f0c91ea9e4
    spec:
      serviceAccountName: newrelic
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: newrelic-infrastructure
        image: newrelic/infrastructure:3.2.40
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-key
              key: new-relic-license-key
        - name: NRI_KUBERNETES_CLUSTER_NAME
          value: "train-ticket-cluster"
        - name: NRI_KUBERNETES_VERBOSE
          value: "0"
        - name: NRIA_DISPLAY_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRI_KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"$(NRI_KUBERNETES_CLUSTER_NAME)"}'
        - name: NRIA_OVERRIDE_HOST_ROOT
          value: ""
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME,CADVISOR_PORT,NRI_KUBERNETES_CLUSTER_NAME,ABSPATH,NRIA_CUSTOM_ATTRIBUTES"
        volumeMounts:
        - name: dev
          mountPath: /dev
          readOnly: true
        - name: host-docker-socket
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: host-volume
          mountPath: /host
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: etc-machine-id
          mountPath: /etc/machine-id
          readOnly: true
        - name: nri-mysql-config
          mountPath: /etc/newrelic-infra/integrations.d/
          readOnly: true
        - name: var-db-newrelic-infra
          mountPath: /var/db/newrelic-infra
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 300m
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: host-docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: host-volume
        hostPath:
          path: /
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: etc-machine-id
        hostPath:
          path: /etc/machine-id
      - name: nri-mysql-config
        configMap:
          name: nri-mysql-config
      - name: var-db-newrelic-infra
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      tolerations:
      - operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "NoExecute"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-mysql-config
  namespace: store
data:
  nri-mysql-config.yml: |
    integrations:
      - name: nri-mysql
        discovery:
          command:
            # Use the following discovery rule to automatically discover MySQL running on Kubernetes
            exec: /var/db/newrelic-infra/nri-discovery-kubernetes --tls --port 10250
          match:
            container.port: 3306
        env:
          # Automatically connect to discovered MySQL instances
          HOSTNAME: ${discovery.ip}
          PORT: 3306
          USERNAME: root
          PASSWORD: root
          REMOTE_MONITORING: true
          EXTENDED_METRICS: true
          EXTENDED_INNODB_METRICS: true
        labels:
          env: production
          cluster: train-ticket
        inventory_source: config/mysql
        interval: 30s